version: "3.5"

services:
    nginx:
        build: .
        container_name: nginx
        ports:
            - 80:80
        networks:
            - testnet


networks: 
    testnet:
        name: testnet
